### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by hackel** [josec89/wakatime-unity#1]
I assumed this project integrated WakaTime with Unity, the default user interface in Ubuntu. That doesn't appear to be the case, as I can make no sense of the limited, cryptic instructions in the README. Please clarify the purpose of this plugin, and why it was worth spamming me about. Thanks.

**Comment by josec89** [comment]
Well, this is awkward.. This is not related to Ubuntu's desktop environment, but to the game editor (https://unity3d.com/) which should be obvious since all plugins are related o an IDE/Editor 

You have probably been notified because you might have asked at any point about a plugin on unity (and wakatime devs assumed that you were referring to the game editor - which appears in the downloads page as being implemented).

Besides, the plugin is under development and so is the documentation (although it should be explanatory enough for an unity3d user)

I apologise for the inconvenience.
Regards.

**Comment by hackel** [comment]
I thought the "other" Unity was a proprietary game engine, not an editor.  In any case, my point was just that you should explicitly specify it in the project description/readme.

**Comment by josec89** [comment]
Well, they define it as: 'a flexible and powerful development platform for creating multiplatform 3D and 2D games and interactive experiences. '. Basically Game Engine + Editor (very similar to UDK).

I changed the readme and I apologise again for the misunderstanding :_).

**Comment by hackel** [comment]
No need to apologise, just glad to understand what it is.  Thanks.
