### ISSUE TITLE
Does not upload time!

### ISSUE THREAD

**Issue by loolo78** [josec89/wakatime-unity#18]
[WakaTimeTest.zip](https://github.com/josec89/wakatime-unity/files/1602167/WakaTimeTest.zip)

Here's an example project. I'm receiving no time logs from this project as all.

**Comment by loolo78** [comment]
Hello?

**Comment by josec89** [comment]
Hey! 

I'm sorry but I really don't have time to keep supporting this project.
One major problem it has is that the wakatime client is injected into the code, instead of downloading the newest version every now and them, so maybe the client is totally outdated.

One thing you can try is to replace the whole `Assets/Editor/WakaTime/client` folder and put there the latest version of the wakatime python client:

https://github.com/wakatime/wakatime

Hope this helped :)

**Comment by loolo78** [comment]
Thank you! Your repo shows up first on google so I assumed you were the primary developer. Thank you for your reply!

**Comment by loolo78** [comment]
Yes updating the wakatime cli client does the trick

**Comment by loolo78** [comment]
Are you part of wakatime or is this a community driven repository?

**Comment by josec89** [comment]
This is community-driven repository: 
I created this repository because I was using wakatime in other IDEs and I wanted to use it in Unity too. 

Feel free to contribute to the repository and fix this major problem :)  
For now I'm going to a _Troubleshooting_ section to the readme
